### ISSUE TITLE
[ISSUE/ BUG] No tori.yaml under configs.

### ISSUE THREAD

**Issue by d2rgaming-9000** [LeoRiether/tori#16]
I am using arch Linux, garuda spin. Gnomes.

I have yay package manager installed.

And whenever I install tori it doesn't produce any tori.yaml files under ~/.config 's

1. Yay -S tori-bin
2. ls ~/.config | grep "tori.yaml" (doesn't return anything, returns ERROR on fish)
3. echo $CONFIG_DIR/tori.yaml (doesn't return anything)
4. echo $XDG_CONFIG_HOME (returns nothing)
5. Try install, remove, then reinstall, still same problem

Expected behavior:
Tori.yaml file supposed to be there

System Information 
 - OS: Garud Linux Gnome, which is ARCH 
 - tori version: latest from the yay packages

Thank you very much.

I will look further what's causing this problem.

Although, ``cargo install tori`` works, I'd like to use yay to get out of the box configurations, as installing  tori via cargo did not allow me to launch the app from command line terminal, wh8ch requires me to do further configs.

**Comment by LeoRiether** [comment]
Hello!
tori does not create the `~/.config/tori.yaml` file, but you can create it yourself by opening the path in a text editor, or running the command `touch ~/.config/tori.yaml` in your terminal. Then, anything you add to this file will override the [default configuration](https://leoriether.github.io/tori/configuration/#defaults). For example, your `tori.yaml` may contain

```yaml
keybindings:
  C-c: CopyUrl
  ';': Add
```

so <kbd>Ctrl+C</kbd>will copy the url of a selected song (by default it quits tori), and <kbd>;</kbd> will add a song or playlist (by default it does nothing).

---

Also, I do realize now that many applications create a config file automatically when you first open it, so I'll consider doing the same in tori :+1:

**Comment by d2rgaming-9000** [comment]
Really love this app btw.

**Comment by d2rgaming-9000** [comment]
Going to close this for now then.

**Comment by d2rgaming-9000** [comment]
Fix : copy the  configurations from site, create a file under /.config, "tori.yaml", and paste the configs there. Save and close.
