### ISSUE TITLE
Switch default bindings so that `q` quits the player

### ISSUE THREAD

**Issue by tranzystorek-io** [LeoRiether/tori#18]
**Is your feature request related to a problem? Please describe.**

Having used `tori` for a while, it still feels quite weird to be closing it with `Ctrl+C` instead of `q`.

**Describe the solution you'd like**

Ideally, we'd ignore SIGINT altogether, set `q` as the quit key, and redesign the queue controls to some other letter.

Alternatively, we could introduce a `<leader>` key, similar to vim, so that we could "namespace" less frequently used or conflicting bindings without changing their keys - `<leader>q` becomes QueueSong in that case for example.

**Comment by LeoRiether** [comment]
Hi! Sorry for taking so long to answer :/

You can already quit the player with `q` with something like this on your `~/.config/tori.yaml`:
```yaml
keybindings:
  q: Quit
  tab: QueueSong
  C-c: Nop
```

You might need to use `normal` instead of `keybindings` depending on your version of tori... ~~I don't really remember when this was changed~~

**Comment by tranzystorek-io** [comment]
I think `u` is unused and as the second letter in the word "queue" should be easy to associate

**Comment by LeoRiether** [comment]
This is now the default behavior in v0.2.3!
