### ISSUE TITLE
bug: index out of bounds when swapping song down

### ISSUE THREAD

**Issue by iagorrr** [LeoRiether/tori#22]
**Describe the bug**

Application crashes when trying to swap down the last song in the playlist 

**To Reproduce**
1. Open tori as usually
2. Go to a non empty playlist
3. Navigate to the last one and press `J` to swap song down
4.  Results in the following error:
```bash
$ tori
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /home/iagorrr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tori-0.2.3/src/app/browse_screen/songs.rs:271:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

Probably nothing

**Screenshots**

![tori](https://github.com/LeoRiether/tori/assets/85769349/81ed1e0f-9601-4eb0-bd48-7553c7bff9ef)

**System Information (please complete the following information):**
 - OS:  Linux manj 6.1.29-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023 x86_64 GNU/Linux

 - tori version : v.0.2.3

**Additional context**

Adding an extra *if* at` tori/src/app/browse_screen/song.rs:269` apparently solves the problem but i am not sure if this is the appropriate way, this change can be found in [this commit](https://github.com/iagorrr/tori/commit/1d7845100108fc9ba0d695b0b4b192c52eb21b18), if that is the right way would be nice to create a new test and then a PR ?

**Comment by LeoRiether** [comment]
Good catch! I pushed a [commit](https://github.com/LeoRiether/tori/commit/d5b4d9d925dbd50c861aae9ca773197e55c2f7fc?diff=split) that fixes this, in a way that's closer to the code for `SwapSongUp`, it should be on the next release. Thank you for the contribution :)

**Comment by iagorrr** [comment]
Nice !
