### ISSUE TITLE
feature: rename playlist

### ISSUE THREAD

**Issue by iagorrr** [LeoRiether/tori#24]
Currently there is no way to rename a playlist pressing 'R', i looked into the source code and found that this is a expected functionality but isn't implemented yet.

Would be nice to press 'R' under a playlist and use the modal to rename a playlist just like is possible when dealing with songs.

**Comment by LeoRiether** [comment]
Fixed in the newly released version, [v0.2.6](https://github.com/LeoRiether/tori/releases/tag/v0.2.6)!
